name: icon_maker
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  cupertino_icons: ^1.0.8
  desktop_drop: ^0.5.0
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5
  riverpod: ^2.6.1
  toastification: ^2.3.0
  window_manager: ^0.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  